server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: travel_route_back
  profiles:
    include: db
  sql:
    init:
      mode: always
  jwt:
    secret: 1234

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  type-aliases-package: com.namagong.travel_route_back.**.domain

logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: debug
      connection: OFF
      sqlonly: debug
      sqltiming: OFF
    '[org.springframework.security]': debug